-- Add raw table flights
CREATE TABLE IF NOT EXISTS flights_raw (
    FlightDate DATE NOT NULL,
    Airline VARCHAR(100) NOT NULL,
    Origin VARCHAR(3) NOT NULL,
    Dest VARCHAR(3) NOT NULL,
    Cancelled BOOLEAN NOT NULL,
    Diverted BOOLEAN NOT NULL,
    CRSDepTime FLOAT NOT NULL,
    DepTime FLOAT,
    DepDelayMinutes FLOAT,
    DepDelay FLOAT,
    ArrTime FLOAT,
    ArrDelayMinutes FLOAT,
    AirTime FLOAT,
    CRSElapsedTime FLOAT,
    ActualElapsedTime FLOAT,
    Distance FLOAT,
    Year INT,
    Quarter INT,
    Month INT,
    DayofMonth INT,
    DayOfWeek INT,

    Marketing_Airline_Network VARCHAR(2) NOT NULL,
    Operated_or_Branded_Code_Share_Partners VARCHAR(12) NOT NULL,
    DOT_ID_Marketing_Airline BIGINT NOT NULL,
    IATA_Code_Marketing_Airline VARCHAR(2) NOT NULL,
    Flight_Number_Marketing_Airline BIGINT NOT NULL,
    Operating_Airline VARCHAR(2) NOT NULL,
    DOT_ID_Operating_Airline BIGINT NOT NULL,
    IATA_Code_Operating_Airline VARCHAR(2) NOT NULL,
    Tail_Number VARCHAR(6),    
    Flight_Number_Operating_Airline BIGINT NOT NULL,
    
    OriginAirportID BIGINT NOT NULL,
    OriginAirportSeqID BIGINT NOT NULL,
    OriginCityMarketID BIGINT NOT NULL,
    OriginCityName VARCHAR(50) NOT NULL,
    OriginState VARCHAR(2) NOT NULL,
    OriginStateFips INT NOT NULL,
    OriginStateName VARCHAR(50) NOT NULL,
    OriginWac INT NOT NULL,
    DestAirportID BIGINT NOT NULL,
    DestAirportSeqID BIGINT NOT NULL,
    DestCityMarketID BIGINT NOT NULL,
    DestCityName VARCHAR(50) NOT NULL,
    DestState VARCHAR(2) NOT NULL,
    DestStateFips INT NOT NULL,
    DestStateName VARCHAR(50) NOT NULL,
    DestWac INT,

    DepDel15 FLOAT,
    DepartureDelayGroups FLOAT,
    DepTimeBlk VARCHAR(9),
    TaxiOut FLOAT,
    WheelsOff FLOAT,
    WheelsOn FLOAT,
    TaxiIn FLOAT,
    CRSArrTime FLOAT,
    ArrDelay FLOAT,
    ArrDel15 FLOAT,
    ArrivalDelayGroups FLOAT,
    ArrTimeBlk VARCHAR(9),
    DistanceGroup INT,
    DivAirportLandings FLOAT
);


-- Add primary table flights
CREATE TABLE IF NOT EXISTS flights (
    FlightDate DATE NOT NULL,
    Airline VARCHAR(100) NOT NULL,
    Origin VARCHAR(3) NOT NULL,
    Dest VARCHAR(3) NOT NULL,
    Cancelled BOOLEAN NOT NULL,
    Diverted BOOLEAN NOT NULL,
    CRSDepTime TIME NOT NULL,
    DepTime TIME,
    DepDelayMinutes INT,
    DepDelay INT,
    ArrTime TIME,
    ArrDelayMinutes INT,
    AirTime INT,
    CRSElapsedTime INT,
    ActualElapsedTime INT,
    Distance INT NOT NULL,
    Year INT NOT NULL,
    Quarter INT NOT NULL,
    Month INT NOT NULL,
    DayofMonth INT NOT NULL,
    DayOfWeek INT NOT NULL,

    Marketing_Airline_Network VARCHAR(2) NOT NULL,
    Operated_or_Branded_Code_Share_Partners VARCHAR(12) NOT NULL,
    DOT_ID_Marketing_Airline BIGINT NOT NULL,
    IATA_Code_Marketing_Airline VARCHAR(2) NOT NULL,
    Flight_Number_Marketing_Airline BIGINT NOT NULL,
    Operating_Airline VARCHAR(2) NOT NULL,
    DOT_ID_Operating_Airline BIGINT NOT NULL,
    IATA_Code_Operating_Airline VARCHAR(2) NOT NULL,
    Tail_Number VARCHAR(6),
    Flight_Number_Operating_Airline BIGINT NOT NULL,

    OriginAirportID BIGINT NOT NULL,
    OriginAirportSeqID BIGINT NOT NULL,
    OriginCityMarketID BIGINT NOT NULL,
    OriginCityName VARCHAR(50) NOT NULL,
    OriginState VARCHAR(2) NOT NULL,
    OriginStateFips INT NOT NULL,
    OriginStateName VARCHAR(50) NOT NULL,
    OriginWac INT NOT NULL,
    DestAirportID BIGINT NOT NULL,
    DestAirportSeqID BIGINT NOT NULL,
    DestCityMarketID BIGINT NOT NULL,
    DestCityName VARCHAR(50) NOT NULL,
    DestState VARCHAR(2) NOT NULL,
    DestStateFips INT NOT NULL,
    DestStateName VARCHAR(50) NOT NULL,
    DestWac INT,

    DepDel15 BOOLEAN,
    DepartureDelayGroups INT,
    DepTimeBlk VARCHAR(9),
    TaxiOut INT,
    WheelsOff TIME,
    WheelsOn TIME,
    TaxiIn INT,
    CRSArrTime TIME,
    ArrDelay INT,
    ArrDel15 BOOLEAN,
    ArrivalDelayGroups INT,
    ArrTimeBlk VARCHAR(9),
    DistanceGroup INT,
    DivAirportLandings INT,
    PRIMARY KEY (
        FlightDate, 
        Marketing_Airline_Network, 
        Flight_Number_Marketing_Airline, 
        OriginAirportID, 
        DestAirportID, 
        CRSDepTime
    )
);
